version: "3.8"

services:
  api:
    build: ./api
    container_name: "API"
    ports:
      - "50050:50050"
  auth-service:
    build:
      context: cmd/AuthService
      dockerfile: Dockerfile
    container_name: "AuthService"
    ports:
      - "50051:50051"
    depends_on:
      - api
  client-test:
    build:
      context: cmd/AuthService
      dockerfile: DockerfileClient
    container_name: "ClientTest"
    ports:
      - "50052:5052"
    depends_on:
      - auth-service
  go-kit-db:
    build:
      context: cmd/Go-Kit
      dockerfile: DockerfileDB
    container_name: "GoKitDB"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgres/data
  go-kit:
    build:
      context: cmd/Go-Kit
      dockerfile: Dockerfile
    container_name: "GoKit"
    ports:
      - "8080:8080"
    depends_on:
      - go-kit-db

volumes:
  db-data:
