version: "3.8"

services:
  api:
    build: ./api
    container_name: "API"
    ports:
      - "50050:50050"
  auth-service:
    build:
      context: cmd/AuthService
      dockerfile: Dockerfile
    container_name: "AuthService"
    ports:
      - "50051:50051"
    depends_on:
      - api
  client-test:
    build:
      context: cmd/AuthService
      dockerfile: DockerfileClient
    container_name: "ClientTest"
    ports:
      - "50052:5052"
    depends_on:
      - auth-service

