version: "3.8"

services:
  api:
    build: ./api
    container_name: "API"
    ports:
      - "50050:50050"
  service1:
    build:
      context: ./cmd/service1
    container_name: "Service1"
    ports:
      - "50051:50051"
    depends_on:
      - api


